[package]
name = "rust-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
futures-intrusive = "0.5.0"
image = "0.25.8"
thiserror = "2.0.17"
wgpu = "27.0.1"
winit = "0.30.12"
